urls.py
from django.contrib import admin
from django.urls import path, include
from apps.categories.views import CategoryListView, TopicListView, TopicCreateView, RegisterUser, LoginUser, logout_user
from apps.comments.views import CommentListView, CommentCreateView, CommentUpdateView, CommentDeleteView
from apps.votes.views import VoteCreateView, VoteDeleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    #path('accounts/', include('allauth.urls')),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('categories/<str:assign>/', TopicListView.as_view()),
    path('categories/<str:assign>/add_topic/', TopicCreateView.as_view()),

    path('categories/<str:assign>/topics/<str:slug>/', CommentListView.as_view()),
    path('categories/<str:assign>/topics/<str:slug>/add_comment/', CommentCreateView.as_view()),
    path('categories/<str:assign>/topics/<str:slug>/comments/<int:pk>/update/', CommentUpdateView.as_view()),
    path('categories/<str:assign>/topics/<str:slug>/comments/<int:pk>/delete/', CommentDeleteView.as_view()),

    path('categories/<str:assign>/topics/<str:slug>/comments/<int:pk>/vote/', VoteCreateView.as_view()),
    path('categories/<str:assign>/topics/<str:slug>/comments/<int:pk>/vote/<int:vote_id>/delete/', VoteDeleteView.as_view()),
]

apps/votes/models.py
from django.db import models


class Vote(models.Model):
    comment = models.ForeignKey('comments.Comment', on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.PROTECT)
    create_at = models.DateTimeField(auto_now_add=True)



    def get_absolute_url(self):
        return f'{self.comment.get_absolute_url()}vote/{self.id}/'

templates/category_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for object in category_list %}
    <a href="{{ object.get_absolute_url }}">{{ object }}</a><br>
{% endfor %}
<br>
{% if request.user.is_authenticated %}
{{user.username}}|<a href="{% url 'logout' %}">Выйти</a>
{% else %}
<a href="{% url 'register' %}">Регистрация</a>|<a href="{% url 'login' %}">Войти</a>
{% endif %}
</body>
</html>

templates/comment_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
    <body>
    {% for comment in comment_list %}
        {{ comment.text }} ({{ comment.vote_set.count }})

        {% if comment.user_id == request.user.id or request.user.is_superuser %}
            <a href="{{ comment.get_absolute_url }}update/">Изменить</a>
        {% endif %}

        {% if comment.user_id == request.user.id or request.user.is_superuser %}
        <form action="{{ comment.get_absolute_url }}delete/" method="POST">
            {% csrf_token %}
            <input type="submit" value="Удалить">
        </form>
        {% endif %}

        {% if comment.user_id == request.user.id or request.user.is_superuser %}
            {% if not comment.user_vote %}
                <form action="{{ comment.get_absolute_url }}vote/" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="comment" value="{{ comment.id }}">
                    <input type="submit" value="Лайк">
                </form>
            {% else %}
                <form action="{{ comment.user_vote.0.get_absolute_url }}delete/" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Отмена лайка">
                </form>
            {% endif %}
        {% endif %}

        <br>
    {% endfor %}
    <br>
    {% include 'pagination.html' %}
    <br>
    <a href="/categories/{{ view.kwargs.assign }}/topics/{{ view.kwargs.slug }}/add_comment/">Добавить комментарий</a>
    </body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">

	<!-- Security token -->
	{% csrf_token %}

	<!-- Using the formset -->
	{{ form.as_p }}

	<button type="submit">Войти</button>
</form>

</body>
</html>

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">

	<!-- Security token -->
	{% csrf_token %}

	<!-- Using the formset -->
	{{ form.as_p }}

	<button type="submit">Регистрация</button>
</form>

</body>
</html>